
name: Daniel Cooper
host: 0.0.0.0

# Exclude files from Jekyll Conversion
exclude: [
	README.md,
	styles/styles.css.map,
	styles/*.less,
	.gitignore,
	CNAME,
	node_modules,
	gulpfile.js,
	package.json,
	package-lock.json,
	Dockerfile
]

include: [
	styles/styles.css
]