
name: Daniel Cooper

# Exclude files from Jekyll Conversion
exclude: [
	README.md,
	styles/styles.css.map,
	styles/*.less,
	.gitignore,
	CNAME,
	node_modules,
	gulpfile.js,
	package.json
]

include: [
	styles/styles.css
]